### ISSUE TITLE
custom classes (styles) for selected dates

### ISSUE THREAD

**Issue by ddtch** [lekhmanrus/ngx-multiple-dates#1]
Hello, is it possible to add somehow custom classes to the selected dates? The case is, I want to show on the calendar different days with different colors. like this 
![image](https://user-images.githubusercontent.com/765596/110081228-0dd3eb00-7da5-11eb-9d7f-4c733e705ef2.png)

**Comment by lekhmanrus** [comment]
Hi @ddtch,
Good suggestion - I'll try to implement it tomorrow or on these weekends.
