### ISSUE TITLE
Can use my custom date pipe for chip?

### ISSUE THREAD

**Issue by IvanYCChen** [lekhmanrus/ngx-multiple-dates#12]
### Feature Description

Hi,
Because I want to customize the week name.
Can add this feature?

**Comment by IvanYCChen** [comment]
Hi,
Because I use Chinese character, 
Chinese's Monday is "週一", this time I want to display like "2022/09/22 (一)"
So I have to transfer month to Chinese by myself
|   English  | Chinese  |
|  ----  | ----  |
| Monday  | (一) |
| Tuesday  | (二) |
| Wednesday | (三) |
| Thursday | (四) |
| Friday | (五) |
| Saturday  | (六) |
| Sunday  | (日) |

**Comment by lekhmanrus** [comment]
You can use a Chinese locale instead. See [LOCALE_ID](https://angular.io/api/core/LOCALE_ID).

**Comment by IvanYCChen** [comment]
Thanks for your teaching.
I success for use LOCALE_ID to satisfy my require
