### ISSUE TITLE
Support angular material's date implementation modules

### ISSUE THREAD

**Issue by vixducis** [lekhmanrus/ngx-multiple-dates#2]
### Feature Description

I'm not sure whether it is possible, but it would be awesome to see support for angular material's date implementation modules (`MatNativeDateModule` , `MatLuxonDateModule `, `MatMomentDateModule `). I see you already support native JS dates and moment, but adding support for the modules functionality means each date implementation will be supported if an adapter is available/written. 

### Use Case

Supporting a wide variety of date implementations besides JS dates and moment.

**Comment by lekhmanrus** [comment]
Hi @gerwintown,
Thank you! Good point. Just released a new version and added documentation to Readme file. 🙂
All Angular Material date adapters are supported now since [ngx-multiple-dates **v13.1.0**](https://github.com/lekhmanrus/ngx-multiple-dates/releases/tag/v13.1.0).
