### ISSUE TITLE
Update to Angular v18

### ISSUE THREAD

**Issue by jmeinlschmidt** [lekhmanrus/ngx-multiple-dates#35]
### Feature Description

Provide support for Angular v18

**Comment by lekhmanrus** [comment]
Hi @jmeinlschmidt,
Thank you! Just released [v18.0.0](https://github.com/lekhmanrus/ngx-multiple-dates/releases/tag/v18.0.0). 🙂

**Comment by jmeinlschmidt** [comment]
@lekhmanrus thank you for taking care of the project🙏
