### ISSUE TITLE
Date Formatting

### ISSUE THREAD

**Issue by nmichniewicz** [lekhmanrus/ngx-multiple-dates#39]
### Documentation Feedback

Hello is it possible to format dates? I saw some basic formatting like 10/1/24 but what if I want something like Mon May 24th is that possible?

**Comment by lekhmanrus** [comment]
Hi @nmichniewicz,
Thanks! 😊
It is actually reflected in our documentation for [MultipleDatesComponent<D = Date>](https://github.com/lekhmanrus/ngx-multiple-dates?tab=readme-ov-file#multipledatescomponentd--date) at
`@Input()`
`format: string`
row:
> The date/time components to include, using predefined options or a custom format string.
> See [DatePipe Usage notes](https://angular.io/api/common/DatePipe#usage-notes) for more information.
